linters-settings:
  govet:
    enable-all: true
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  timeout: 5m
