// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agentos/v1/catalog_ingest.proto

package agentosv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/neurosai/agentos/pkg/api/proto/agentos/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CatalogIngestServiceName is the fully-qualified name of the CatalogIngestService service.
	CatalogIngestServiceName = "agentos.v1.CatalogIngestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CatalogIngestServiceUpsertObservationsProcedure is the fully-qualified name of the
	// CatalogIngestService's UpsertObservations RPC.
	CatalogIngestServiceUpsertObservationsProcedure = "/agentos.v1.CatalogIngestService/UpsertObservations"
)

// CatalogIngestServiceClient is a client for the agentos.v1.CatalogIngestService service.
type CatalogIngestServiceClient interface {
	UpsertObservations(context.Context) *connect.ClientStreamForClient[v1.Observation, v1.UpsertObservationsResponse]
}

// NewCatalogIngestServiceClient constructs a client for the agentos.v1.CatalogIngestService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCatalogIngestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CatalogIngestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	catalogIngestServiceMethods := v1.File_agentos_v1_catalog_ingest_proto.Services().ByName("CatalogIngestService").Methods()
	return &catalogIngestServiceClient{
		upsertObservations: connect.NewClient[v1.Observation, v1.UpsertObservationsResponse](
			httpClient,
			baseURL+CatalogIngestServiceUpsertObservationsProcedure,
			connect.WithSchema(catalogIngestServiceMethods.ByName("UpsertObservations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// catalogIngestServiceClient implements CatalogIngestServiceClient.
type catalogIngestServiceClient struct {
	upsertObservations *connect.Client[v1.Observation, v1.UpsertObservationsResponse]
}

// UpsertObservations calls agentos.v1.CatalogIngestService.UpsertObservations.
func (c *catalogIngestServiceClient) UpsertObservations(ctx context.Context) *connect.ClientStreamForClient[v1.Observation, v1.UpsertObservationsResponse] {
	return c.upsertObservations.CallClientStream(ctx)
}

// CatalogIngestServiceHandler is an implementation of the agentos.v1.CatalogIngestService service.
type CatalogIngestServiceHandler interface {
	UpsertObservations(context.Context, *connect.ClientStream[v1.Observation]) (*connect.Response[v1.UpsertObservationsResponse], error)
}

// NewCatalogIngestServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCatalogIngestServiceHandler(svc CatalogIngestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	catalogIngestServiceMethods := v1.File_agentos_v1_catalog_ingest_proto.Services().ByName("CatalogIngestService").Methods()
	catalogIngestServiceUpsertObservationsHandler := connect.NewClientStreamHandler(
		CatalogIngestServiceUpsertObservationsProcedure,
		svc.UpsertObservations,
		connect.WithSchema(catalogIngestServiceMethods.ByName("UpsertObservations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentos.v1.CatalogIngestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CatalogIngestServiceUpsertObservationsProcedure:
			catalogIngestServiceUpsertObservationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCatalogIngestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCatalogIngestServiceHandler struct{}

func (UnimplementedCatalogIngestServiceHandler) UpsertObservations(context.Context, *connect.ClientStream[v1.Observation]) (*connect.Response[v1.UpsertObservationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentos.v1.CatalogIngestService.UpsertObservations is not implemented"))
}
