// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agentos/v1/task_events.proto

package agentosv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/neurosai/agentos/pkg/api/proto/agentos/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskEventsServiceName is the fully-qualified name of the TaskEventsService service.
	TaskEventsServiceName = "agentos.v1.TaskEventsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskEventsServiceStreamTaskEventsProcedure is the fully-qualified name of the TaskEventsService's
	// StreamTaskEvents RPC.
	TaskEventsServiceStreamTaskEventsProcedure = "/agentos.v1.TaskEventsService/StreamTaskEvents"
)

// TaskEventsServiceClient is a client for the agentos.v1.TaskEventsService service.
type TaskEventsServiceClient interface {
	StreamTaskEvents(context.Context, *connect.Request[v1.StreamTaskEventsRequest]) (*connect.ServerStreamForClient[v1.TaskEvent], error)
}

// NewTaskEventsServiceClient constructs a client for the agentos.v1.TaskEventsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskEventsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskEventsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskEventsServiceMethods := v1.File_agentos_v1_task_events_proto.Services().ByName("TaskEventsService").Methods()
	return &taskEventsServiceClient{
		streamTaskEvents: connect.NewClient[v1.StreamTaskEventsRequest, v1.TaskEvent](
			httpClient,
			baseURL+TaskEventsServiceStreamTaskEventsProcedure,
			connect.WithSchema(taskEventsServiceMethods.ByName("StreamTaskEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskEventsServiceClient implements TaskEventsServiceClient.
type taskEventsServiceClient struct {
	streamTaskEvents *connect.Client[v1.StreamTaskEventsRequest, v1.TaskEvent]
}

// StreamTaskEvents calls agentos.v1.TaskEventsService.StreamTaskEvents.
func (c *taskEventsServiceClient) StreamTaskEvents(ctx context.Context, req *connect.Request[v1.StreamTaskEventsRequest]) (*connect.ServerStreamForClient[v1.TaskEvent], error) {
	return c.streamTaskEvents.CallServerStream(ctx, req)
}

// TaskEventsServiceHandler is an implementation of the agentos.v1.TaskEventsService service.
type TaskEventsServiceHandler interface {
	StreamTaskEvents(context.Context, *connect.Request[v1.StreamTaskEventsRequest], *connect.ServerStream[v1.TaskEvent]) error
}

// NewTaskEventsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskEventsServiceHandler(svc TaskEventsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskEventsServiceMethods := v1.File_agentos_v1_task_events_proto.Services().ByName("TaskEventsService").Methods()
	taskEventsServiceStreamTaskEventsHandler := connect.NewServerStreamHandler(
		TaskEventsServiceStreamTaskEventsProcedure,
		svc.StreamTaskEvents,
		connect.WithSchema(taskEventsServiceMethods.ByName("StreamTaskEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentos.v1.TaskEventsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskEventsServiceStreamTaskEventsProcedure:
			taskEventsServiceStreamTaskEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskEventsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskEventsServiceHandler struct{}

func (UnimplementedTaskEventsServiceHandler) StreamTaskEvents(context.Context, *connect.Request[v1.StreamTaskEventsRequest], *connect.ServerStream[v1.TaskEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentos.v1.TaskEventsService.StreamTaskEvents is not implemented"))
}
