// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agentos/v1/catalog_ingest.proto

package agentosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Collector     string                 `protobuf:"bytes,2,opt,name=collector,proto3" json:"collector,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ResourceRef   string                 `protobuf:"bytes,5,opt,name=resource_ref,json=resourceRef,proto3" json:"resource_ref,omitempty"`
	ClaimJson     []byte                 `protobuf:"bytes,6,opt,name=claim_json,json=claimJson,proto3" json:"claim_json,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_agentos_v1_catalog_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_agentos_v1_catalog_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_agentos_v1_catalog_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *Observation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Observation) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (x *Observation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Observation) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *Observation) GetResourceRef() string {
	if x != nil {
		return x.ResourceRef
	}
	return ""
}

func (x *Observation) GetClaimJson() []byte {
	if x != nil {
		return x.ClaimJson
	}
	return nil
}

func (x *Observation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type UpsertObservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertObservationsResponse) Reset() {
	*x = UpsertObservationsResponse{}
	mi := &file_agentos_v1_catalog_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertObservationsResponse) ProtoMessage() {}

func (x *UpsertObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentos_v1_catalog_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertObservationsResponse.ProtoReflect.Descriptor instead.
func (*UpsertObservationsResponse) Descriptor() ([]byte, []int) {
	return file_agentos_v1_catalog_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertObservationsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *UpsertObservationsResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

var File_agentos_v1_catalog_ingest_proto protoreflect.FileDescriptor

const file_agentos_v1_catalog_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1fagentos/v1/catalog_ingest.proto\x12\n" +
	"agentos.v1\"\xd2\x01\n" +
	"\vObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tcollector\x18\x02 \x01(\tR\tcollector\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1f\n" +
	"\vobserved_at\x18\x04 \x01(\tR\n" +
	"observedAt\x12!\n" +
	"\fresource_ref\x18\x05 \x01(\tR\vresourceRef\x12\x1d\n" +
	"\n" +
	"claim_json\x18\x06 \x01(\fR\tclaimJson\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\"T\n" +
	"\x1aUpsertObservationsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected2o\n" +
	"\x14CatalogIngestService\x12W\n" +
	"\x12UpsertObservations\x12\x17.agentos.v1.Observation\x1a&.agentos.v1.UpsertObservationsResponse(\x01B@Z>github.com/neurosai/agentos/pkg/api/proto/agentos/v1;agentosv1b\x06proto3"

var (
	file_agentos_v1_catalog_ingest_proto_rawDescOnce sync.Once
	file_agentos_v1_catalog_ingest_proto_rawDescData []byte
)

func file_agentos_v1_catalog_ingest_proto_rawDescGZIP() []byte {
	file_agentos_v1_catalog_ingest_proto_rawDescOnce.Do(func() {
		file_agentos_v1_catalog_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentos_v1_catalog_ingest_proto_rawDesc), len(file_agentos_v1_catalog_ingest_proto_rawDesc)))
	})
	return file_agentos_v1_catalog_ingest_proto_rawDescData
}

var file_agentos_v1_catalog_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agentos_v1_catalog_ingest_proto_goTypes = []any{
	(*Observation)(nil),                // 0: agentos.v1.Observation
	(*UpsertObservationsResponse)(nil), // 1: agentos.v1.UpsertObservationsResponse
}
var file_agentos_v1_catalog_ingest_proto_depIdxs = []int32{
	0, // 0: agentos.v1.CatalogIngestService.UpsertObservations:input_type -> agentos.v1.Observation
	1, // 1: agentos.v1.CatalogIngestService.UpsertObservations:output_type -> agentos.v1.UpsertObservationsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agentos_v1_catalog_ingest_proto_init() }
func file_agentos_v1_catalog_ingest_proto_init() {
	if File_agentos_v1_catalog_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentos_v1_catalog_ingest_proto_rawDesc), len(file_agentos_v1_catalog_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentos_v1_catalog_ingest_proto_goTypes,
		DependencyIndexes: file_agentos_v1_catalog_ingest_proto_depIdxs,
		MessageInfos:      file_agentos_v1_catalog_ingest_proto_msgTypes,
	}.Build()
	File_agentos_v1_catalog_ingest_proto = out.File
	file_agentos_v1_catalog_ingest_proto_goTypes = nil
	file_agentos_v1_catalog_ingest_proto_depIdxs = nil
}
