// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agentos/v1/task_events.proto

package agentosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	mi := &file_agentos_v1_task_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_agentos_v1_task_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_agentos_v1_task_events_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskRef) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_agentos_v1_task_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agentos_v1_task_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_agentos_v1_task_events_proto_rawDescGZIP(), []int{1}
}

func (x *TaskEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *TaskEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *TaskEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type StreamTaskEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FromBeginning bool                   `protobuf:"varint,2,opt,name=from_beginning,json=fromBeginning,proto3" json:"from_beginning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskEventsRequest) Reset() {
	*x = StreamTaskEventsRequest{}
	mi := &file_agentos_v1_task_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskEventsRequest) ProtoMessage() {}

func (x *StreamTaskEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentos_v1_task_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskEventsRequest) Descriptor() ([]byte, []int) {
	return file_agentos_v1_task_events_proto_rawDescGZIP(), []int{2}
}

func (x *StreamTaskEventsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamTaskEventsRequest) GetFromBeginning() bool {
	if x != nil {
		return x.FromBeginning
	}
	return false
}

var File_agentos_v1_task_events_proto protoreflect.FileDescriptor

const file_agentos_v1_task_events_proto_rawDesc = "" +
	"\n" +
	"\x1cagentos/v1/task_events.proto\x12\n" +
	"agentos.v1\"6\n" +
	"\aTaskRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xb2\x01\n" +
	"\tTaskEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\fR\vpayloadJson\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"Y\n" +
	"\x17StreamTaskEventsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0efrom_beginning\x18\x02 \x01(\bR\rfromBeginning2e\n" +
	"\x11TaskEventsService\x12P\n" +
	"\x10StreamTaskEvents\x12#.agentos.v1.StreamTaskEventsRequest\x1a\x15.agentos.v1.TaskEvent0\x01B@Z>github.com/neurosai/agentos/pkg/api/proto/agentos/v1;agentosv1b\x06proto3"

var (
	file_agentos_v1_task_events_proto_rawDescOnce sync.Once
	file_agentos_v1_task_events_proto_rawDescData []byte
)

func file_agentos_v1_task_events_proto_rawDescGZIP() []byte {
	file_agentos_v1_task_events_proto_rawDescOnce.Do(func() {
		file_agentos_v1_task_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentos_v1_task_events_proto_rawDesc), len(file_agentos_v1_task_events_proto_rawDesc)))
	})
	return file_agentos_v1_task_events_proto_rawDescData
}

var file_agentos_v1_task_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agentos_v1_task_events_proto_goTypes = []any{
	(*TaskRef)(nil),                 // 0: agentos.v1.TaskRef
	(*TaskEvent)(nil),               // 1: agentos.v1.TaskEvent
	(*StreamTaskEventsRequest)(nil), // 2: agentos.v1.StreamTaskEventsRequest
}
var file_agentos_v1_task_events_proto_depIdxs = []int32{
	2, // 0: agentos.v1.TaskEventsService.StreamTaskEvents:input_type -> agentos.v1.StreamTaskEventsRequest
	1, // 1: agentos.v1.TaskEventsService.StreamTaskEvents:output_type -> agentos.v1.TaskEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agentos_v1_task_events_proto_init() }
func file_agentos_v1_task_events_proto_init() {
	if File_agentos_v1_task_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentos_v1_task_events_proto_rawDesc), len(file_agentos_v1_task_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentos_v1_task_events_proto_goTypes,
		DependencyIndexes: file_agentos_v1_task_events_proto_depIdxs,
		MessageInfos:      file_agentos_v1_task_events_proto_msgTypes,
	}.Build()
	File_agentos_v1_task_events_proto = out.File
	file_agentos_v1_task_events_proto_goTypes = nil
	file_agentos_v1_task_events_proto_depIdxs = nil
}
